Breaking the workflow

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -32,3 +32,7 @@ jobs:
       - name: printing runner OS
         run: | 
           echo "runner OS: ${{runner.os}}"
+
+# Breaking the code intentionally to see the failure in the workflow
+      - name: breaking the code
+        run: exit 1
